name: Hello World Workflow

# Trigger the workflow on push to the main branch
on: 
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run a simple "Hello, World!" script
      - name: Run Hello World
        run: echo "Hello, World!"
